import { GeistSans } from 'geist/font/sans';
import './globals.css';
import Header from './layout/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Header/>
        <main>{children}</main>
      </body>
    </html>
  );
}
